// Code generated by "stringer -type=PostType"; DO NOT EDIT.

package picopub

import "strconv"

const _PostType_name = "UnknownEntryReadLike"

var _PostType_index = [...]uint8{0, 7, 12, 16, 20}

func (i PostType) String() string {
	if i < 0 || i >= PostType(len(_PostType_index)-1) {
		return "PostType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PostType_name[_PostType_index[i]:_PostType_index[i+1]]
}
